map_type: costmap

# z轴：从地下1m撑到地上10m，配合velodyne_z_filter使用
origin_z: -1.0
z_resolution: 0.1
z_voxels: 110

transform_tolerance: 0.5
meter_scoring: true

footprint: [[-0.21, -0.165], [-0.21, 0.165], [0.21, 0.165], [0.21, -0.165]]
footprint_padding: 0.02

plugins:
- {name: obstacles_layer, type: "costmap_2d::VoxelLayer"}
- {name: inflater_layer, type: "costmap_2d::InflationLayer"}

obstacles_layer:
  # 高度限制完全放开（由 velodyne_z_filter 在点云层控制 0.2~2.0m）
  min_obstacle_height: -100.0
  max_obstacle_height:  100.0

  observation_sources: velodyne
  velodyne:
    sensor_frame: velodyne
    data_type: PointCloud2
    topic: /mid/points_filtered   # 经过 z 过滤的点云
    marking: true
    clearing: true
    min_obstacle_height: -100.0
    max_obstacle_height:  100.0
    obstacle_range: 5.0
    raytrace_range: 6.0

inflater_layer:
  inflation_radius: 0.15
  cost_scaling_factor: 20.0
